const CREATE_STATUS = 201;
const BAD_REQUEST_STATUS = 400;
const UNAUTHORIZED_STATUS = 401;
const FORBIDDEN_STATUS = 403;
const CONFLICT_STATUS = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  CREATE_STATUS,
  BAD_REQUEST_STATUS,
  UNAUTHORIZED_STATUS,
  FORBIDDEN_STATUS,
  CONFLICT_STATUS,
  INTERNAL_SERVER_ERROR,
};
