version: "3.8"
services:
  database:
    container_name: robinhood-database
    ports:
      - 27017:27017
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: .env.example
    volumes:
      - ./resources/db:/data/db

  backend:
    container_name: robinhood-backend
    ports:
      - 2000:2000
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env.example
    environment:
      - PORT=2000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
